### PR TITLE
municipalities updates with data from ANPR

### PR DESCRIPTION
**Pull request by guglielmo**
Data taken from the ANPR web site are integrated into the `_MUNICIPALITIES` data structure, to take into account more codes, especially of ancient and expired locations. 
Also, this is up to date as of November 2019.

This is useful when trying to compute fiscal codes for historical persons.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Hi @guglielmo, thank you very much for this PR.
I checked the data and there are multiple entries for the same code and municipality name.
When the data is indexed the latest value would override the previous ones. This could cause some unexpected behavior that should be tested better before release a new version.

**Comment by fabiocaccamo** [comment]
Hi @guglielmo , I looked better the data, the same municipality code sometimes is listed multiple times, this occurs when a municipality changed province or has been suppressed. 

The information you added are useful, but are not enough to write a better algorithm. 

To improve encoding/decoding accuracy to a next level we should know the last year of validity for each obsolete municipality. Only having this information it will be possible to encode/encode correctly all old codes. 

Do you think you could obtain and add this information? 

The result should be something like this:

```python
# ...
{ "code": "A072", "province": "AL", "name": "AGLIANO (soppresso)", valid_until: 1964 },
{ "code": "A072", "province": "AT", "name": "AGLIANO (soppresso)", valid_until: 1983 },
{ "code": "A072", "province": "AT", "name": "AGLIANO TERME" },
# ...
```

**Comment by fabiocaccamo** [comment]
Could you also link your data-source please?

**Comment by guglielmo** [comment]
Hi @fabiocaccamo, the source is: https://www.anpr.interno.it/portale/anpr-archivio-comuni.csv
There are many information there and each record has a start and end date. So, you could write a valid_from and valid_until with very specific dates.

**Comment by guglielmo** [comment]
I see that the PR was merged and it is now in master. Is it going to be published to PyPi?

**Comment by fabiocaccamo** [comment]
You can install `0.3.6` version.

**Pull request merged**
